FROM nginx:latest

WORKDIR /usr/share/nginx/html

#put your html code in www
COPY www www

#buil a image 
# docker build -t enguillem/nginx .

#run a image
# docker container run -p 80:80 --rm --name enguillem_nginx enguillem/nginx

